var firstname = "Samrith";
var lastname ="Gangasani";
var fullname =firstname.concat(lastname);
console.log(fullname);
document.getElementById("ex1").innerHTML=fullname;
var fruitarray =["orange","banana","grape"];
fruitarray.reverse();
console.log(fruitarray);
document.getElementById("ex2").innerHTML=fruitarray;
var element =fruitarray[0];
console.log(element);
document.getElementById("ex3").innerHTML=element;
var len= fruitarray.length;
console.log(len);
document.getElementById("ex3").innerHTML=len;
var numarray =["10","1","30","2"];
console.log(numarray);
document.getElementById("ex4").innerHTML=numarray;
var maxnum =Math.max.apply(Math,numarray);
console.log(maxnum);
document.getElementById("ex5").innerHTML=maxnum;